name: Calculate SHA-256

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'URL of the file to download and calculate SHA-256'
        required: true
      calculate_sha256:
        description: 'Whether to calculate SHA-256 hash'
        required: false
        default: 'false'

jobs:
  calculate_sha256:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download file
        run: |
          curl -o downloaded_file ${{ github.event.inputs.url }}
        shell: bash

      - name: Calculate SHA-256
        id: sha256
        if: ${{ github.event.inputs.calculate_sha256 == 'true' }}
        run: |
          SHA256_HASH=$(sha256sum downloaded_file | awk '{ print $1 }')
          echo "SHA-256: $SHA256_HASH"
          echo "::set-output name=sha256::$SHA256_HASH"
        shell: bash

      - name: Print SHA-256 to log
        if: ${{ github.event.inputs.calculate_sha256 == 'true' }}
        run: echo "SHA-256 hash of the downloaded file is: ${{ steps.sha256.outputs.sha256 }}"
        shell: bash

      - name: Skip SHA-256 calculation
        if: ${{ github.event.inputs.calculate_sha256 != 'true' }}
        run: echo "SHA-256 calculation skipped."
        shell: bash