name: publish

on:
  workflow_dispatch:

# on:
#   pull_request:
#     branches:
#       - main

jobs:
  publish-release:
    permissions: write-all 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: iDSK
            asset_name: iDSK-linux-amd64
          - os: macos-latest
            artifact_name: iDSK
            asset_name: iDSK-macos-amd64

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install zip
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get install zip

    - name: Extract version from VERSION file
      id: extract_version
      run: |
        VERSION=$(cat VERSION)
        echo "Version: $VERSION"
        echo "::set-output name=version::$VERSION"

    - name: make idsk
      run: |
        [ -d "bin" ] && rm -r "bin"
        mkdir bin
        make clean
        make
        

    - name: upload amstrad console
      uses: actions/upload-artifact@v4
      with:
        name: iDSK-${{ matrix.os }}
        path: bin/iDSK
  

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: v${{ steps.extract_version.outputs.version }}
        overwrite: true
        body: "new version"