# CPCEMU.MSG (v1.5) - Message file (do not change!)  -- 0. English
NO TOKEN
#ENDIF
#IFCPC
AMSDOS disabled
AMSDOS speedup
Break mask
Colour screen
Company Name
CPC Type
CRTC Type
Data File
Drive A
Drive A: autostart
Drive A: side
Drive A: writeprotected
Drive B
Drive B: autostart
Drive B: side
Drive B: writeprotected
EMS enabled
Emulation delay
Emulation speed
Help file
Interrupt frequency
Interrupt resume
JOY0 calibrate
JOY1 calibrate
Cursor Keys as joystick 0
Size of virtual joystick
KBD Language
Language
M4 enabled
Mouse enabled
Mouse type
Multimode update
Palette change
Poke Database
PPI 50Hz
PPI exp signal
Printer
RAM size
RAM extension type
Realtime
ROM block
ROM path
SB delay
SB delay0
SB DMA buf
SB sample rate
SB stereo
Screen offset
SD card operation mode
Show config
Snapshot
Sound device
Sound enabled
Sound FX enabled
Tape bypass
Tape path
TMP path
Video mode
Virtual KBD Language
VSYNC position
Setup Menu
___Emulation
___Screen
___Sound
___M4_Board
___Control
___PPI_Settings
___Misc
JOY0 calibrate
JOY1 calibrate
Start web server
Stop web server
Load Configuration
Load firmware ROM block
Restart Emulation
Save Configuration
Poke Database
DOS Shell
Continue
Save Snapshot
Save Snapshot
Snapshot Size
Insert Disk
Insert Disk
Drive number
Side Select
Write Protected
Autostart
Select ROM file
Select lower ROM file
Select upper ROM file
Block offset in file
BRK: Assert error!
BRK: User breakpoint (ED FC FC)
CASSETTE: File not open
CASSETTE: Filename too long.
CASSETTE: File: EOF found.
CASSETTE: File write error.
CASSETTE: Nothing saved.
CASSETTE: Nothing loaded.
CASSETTE: Unknown user function
CIO: File already open:
CIO: File not open:
CIO: File not found:
CIO: File not created:
CIO: EOF in file
CIO: Write error in file
CIO: Unknown error in file
CIO: File successfully loaded:
CIO: File successfully saved:
Poke Database
DBASE: Error opening
EMS: Allocate error
EMS: Sorry, at least LIM EMS 4.0 needed
EMS: Not installed.
EMS: Standard EMM segment at:
EMS: Minimal physical segment:
EMS: New minimal physical segment:
EMS: Physical page/segment:
 (too low)
 not in order
EMS: 6 pages in order found
EMS: Using EMM segment at:
EMS: Cannot map page
EMS: Total/free/needed pages:
EMS: Pages allocated:
EMS: Not enough free pages!
EMS: error
EMS: error 80: internal software error
EMS: error 81: hardware malfunction
EMS: error 82: unknown error
EMS: error 83: unallocated or invalid handle
EMS: error 84: undefined function requested
EMS: error 85: no handles available
EMS: error 86: error in save or restore of mapping context
EMS: error 87: more pages requested than physically exist
EMS: error 88: more pages requested than currently available
EMS: error 89: zero pages requested
EMS: error 8A: invalid logical page number
EMS: error 8B: illegal physical page number
EMS: error 8C: context stack out of memory
EMS: error 8D: context save failed, handle already has context stack
EMS: error 8E: context restore failed, no context stack for handle
EMS: error 8F: invalid subfunction
EMS: error 90: undefined attribute type
EMS: error 91: feature not supported
GUS: ULTRASND environment variable not set!
GUS: Initialization failed!
Help
INTRODUCTION
TABLE OF CONTENTS
Topic not found:
INIT: Sorry, using conventional memory.
IO_PORT: Unknown port number:
IO_PORT: Cannot open printer file
IO_PORT: Unknown error
Joystick 0 not found.
Joystick 1 not found.
Move joystick 0 to upper left, press button 1 (or ESC):
Move joystick 0 to lower right, press button 0 (or ESC):
Move joystick 1 to upper left, press button 1 (or ESC):
Move joystick 1 to lower right, press button 0 (or ESC):
Use the setting
Press a key
Sound is off.
Sound is on.
KBD: Function key pressed:
KBD: Unknown function key:
KBD: Unknown special key:
MEM: Bytes free/needed:
MEM: Not enough memory!
ROM: AMSDOS disabled.
ROM: AMSDOS+ disabled.
ROM: AMSDOS speedup installed.
ROM: AMSDOS+ speedup installed.
ROM: Cannot open file
ROM: Error in file
ROM: new(): no memory!
ROM: No AMSDOS ROM found.
ROM: No foreground ROM found.
ROM: ROM already loaded:
ROM: TAPE bypass installed.
ROM: Unknown ROM version.
ROM: CPC 464 detected. (c) Amstrad and Locomotive 1984, 1985
ROM: CPC 664 detected. (c) Amstrad and Locomotive 1984, 1985
ROM: CPC 6128 detected. (c) Amstrad and Locomotive 1984, 1985
ROM: CPC 464+ detected. (c) Amstrad and Locomotive 1984, 1985
ROM: CPC 6128+ detected. (c) Amstrad and Locomotive 1984, 1985
ROM: KC compact detected. (c) Amstrad and Locomotive 1984, 1985
SB: BLASTER environment variable not set!
SB: Warning: unknown BLASTER option
SB: Adlib card found at address:
SB: No Adlib card found at address:
SCREEN: Not enough memory!
SEL: TMP environment variable not set!
SEL: Cannot get TMP file.
SEL: Writing in ZIP file ignored:
SEL: Cannot open file:
SEL: Cannot remove file:
SEL: Cannot rename file:
SEL: File removed:
SELECT: Not enough memory!
SELECT: Not a disk image file!
Last time selected:
Save to Tape
Load from Tape
Catalog
Load Snapshot
Save Configuration
Load Configuration
File selected:
No file selected.
FILE SELECTION
SETUP: Cannot open file
SETUP: Do not overwrite master configuration file CPCEMU.CFG!
SETUP: Warning: COMSPEC environment variable not set!
SETUP: Cannot execute command.
Configuration File created by CPCEMU (v1.5) on
SNAP: Cannot open file
Warning: Not a snapshot file!
SNAP: Version not supported:
Snapshot size not supported:
Not enough memory to load a snapshot of
Loading only 64KB !!
Maybe it will not run on this CPC!
Hey, you have not enough RAM! Size changed to 64KB.
 was saved on a CPC 464.
 was saved on a CPC 664.
 was saved on a CPC 6128.
 was saved on a CPC 464+.
 was saved on a CPC 6128+.
 was saved on a KC compact.
 was saved on a CPC ???
SPK: Initialized.
SWAP: Cannot get swapfile. Using
SWAP: Unable to shrink DOS memory block.
SWAP: Unable to save program to memory or disk.
SWAP: DOS exec call failed.  Error is
SWAP: Bad function.
SWAP: Program file not found.
SWAP: Access to program file denied.
SWAP: Insufficient memory to run program.
SWAP: Bad environment.
SWAP: Bad format.
SWAP: Unexpected error code
ZIF: Unknown error!
ZIP: Cannot open file
ZIP: File too short
ZIP: Read error
ZIP: End of central directory not found
ZIP: Central directory not found
ZIP: Multi volume not supported
ZIP: Central header signature not found
# CPCEMU.MSG ----------------------------------- 1. German
NO TOKEN
#ENDIF
#IFCPC
AMSDOS abgeschaltet
AMSDOS-Beschleunigung
Unterbrechungs-Maske
Farbbildschirm
Firmenname
CPC-Typ
CRTC-Typ
Datendatei
Laufwerk A
Laufwerk A: Autostart
Laufwerk A: Seite
Laufwerk A: Schreibschutz
Laufwerk B
Laufwerk B: Autostart
Laufwerk B: Seite
Laufwerk B: Schreibschutz
EMS erlaubt
Emulations-Verzögerung
Emulations-Geschwindigkeit
Hilfsdatei
Interrupt-Frequenz
Interrupts nachholen
Joy0 kalibrieren
Joy1 kalibrieren
Cursor-Tasten als Joystick 0
Größe des virt. Joysticks
Tastatur-Layout
Sprache
M4 erlaubt
Maus erlaubt
Maustyp
Multimodes auffrischen
Paletten-Änderung
Poke-Datenbank
PPI_50Hz
PPI_EXP_Signal
Drucker
RAM-Größe
RAM-Erweiterungstyp
Echtzeit
ROM-Block
ROM-Pfad
SB-Verzögerung
SB-Verzögerung0
SB-DMA-Puffer
SB-Sampling-Rate
SB-Stereo
Bildschirm-Verschiebung
SD-Card-Betriebsmodus
Zeige Konfiguration
Schnappschuß
Sound-Ausgabegerät
Sound erlaubt
Soundeffekte erlaubt
Kassetten-Umleitung
Kassetten-Pfad
TMP-Pfad
Video-Modus
Layout der virtuellen Tastatur
VSYNC-Position
Setup-Menü
___Emulation
___Bildschirm
___Sound
___M4_Board
___Steuerung
___PPI-Einstellungen
___Sonstiges
Joy0 kalibrieren
Joy1 kalibrieren
Webserver starten
Webserver stoppen
Lade Konfiguration
Lade Firmware-ROM-Block
Neustart der Emulation
Speichere Konfiguration
Poke-Datenbank
DOS-Shell
Fortsetzen
Schnappschuß speichern
Speichere Schnappschuß
Schnappschußgröße
Diskette einlegen
Diskette einlegen
Laufwerk
Diskettenseite
Schreibschutz
Autostart
ROM-Datei auswählen
Wähle Datei für unteres ROM
Wähle Datei für oberes ROM
Block-Nummer in Datei
BRK: Assert-Fehler!
BRK: Benutzer-Unterbrechungspunkt (ED FC FC)
CASSETTE: Datei nicht geöffnet
CASSETTE: Dateiname zu lang.
CASSETTE: Datei: EOF gefunden.
CASSETTE: Datei: Schreibfehler.
CASSETTE: Nichts gespeichert.
CASSETTE: Nichts geladen.
CASSETTE: Unbekannte Benutzer-Funktion
CIO: Datei schon geöffnet:
CIO: Datei nicht geöffnet:
CIO: Datei nicht gefunden:
CIO: Datei nicht erzeugt:
CIO: EOF in Datei
CIO: Schreibfehler in Datei
CIO: Unbekannter Fehler in Datei
CIO: Datei erfolgreich geladen:
CIO: Datei erfolgreich gespeichert:
Poke-Datenbank
DBASE: Fehler beim Öffnen von
EMS: Allokierungs-Fehler
EMS: Schade, es wird mindestens LIM EMS 4.0 benötigt.
EMS: Nicht installiert.
EMS: Standard EMM-Segment an:
EMS: Minimales physikalisches Segment:
EMS: Neues minimales physikalisches Segment:
EMS: Physikalische Seite/Segment:
 (zu klein)
 nicht aufsteigend
EMS: 6 aufsteigende Seiten gefunden.
EMS: Benutze EMM-Segment an:
EMS: Kann Seite nicht umschalten:
EMS: Gesamte/freie/benötigte Seiten:
EMS: Allokierte Seiten:
EMS: Nicht genug freie Seiten!
EMS: Fehler
EMS: Fehler 80: interner Software-Fehler
EMS: Fehler 81: Hardware-Fehlfunktion
EMS: Fehler 82: unbekannter Fehler
EMS: Fehler 83: unallokierter oder fehlerhafter Handle
EMS: Fehler 84: undefinierte Funktion aufgerufen
EMS: Fehler 85: keine Handles verfügbar
EMS: Fehler 86: Fehler in Speichern oder Wiederherstellen des Kontextes
EMS: Fehler 87: Mehr Seiten angefordert als physikalisch verfügbar
EMS: Fehler 88: Mehr Seiten angefordert als gerade verfügbar
EMS: Fehler 89: keine Seiten angefordert
EMS: Fehler 8A: ungültige logische Seitennummer
EMS: Fehler 8B: ungültige physikalische Seitennummer
EMS: Fehler 8C: Kontext-Stapel hat kein Speicher mehr
EMS: Fehler 8D: Kontext-Abspeichern fehlgeschlagen, Handle hat schon Kontext
EMS: Fehler 8E: Kontext-Wiederherstellen fehlgeschlagen, Handle ohne Kontext
EMS: Fehler 8F: ungültige Unterfunktion
EMS: Fehler 90: Undefinierter Attribut-Typ
EMS: Fehler 91: Funktion nicht unterstützt
GUS: ULTRASND-Umgebungsvariable nicht gesetzt!
GUS: Initialisierung fehlgeschlagen!
Hilfe
EINFÜHRUNG
INHALTSVERZEICHNIS
Thema nicht gefunden:
INIT: Schade, muß konventionellen Speicher benutzen.
IO_PORT: Unbekannte Port-Nummer:
IO_PORT: Kann Drucker-Datei nicht öffnen:
IO_PORT: Unbekannter Fehler!
Joystick 0 nicht gefunden.
Joystick 1 nicht gefunden.
Bewege Joystick 0 nach links oben, drücke Feuer 1 (ESC):
Bewege Joystick 0 nach rechts unten, drücke Feuer 0 (ESC):
Bewege Joystick 1 nach links oben, drücke Feuer 1 (ESC):
Bewege Joystick 1 nach rechts unten, drücke Feuer 0 (ESC):
Benutze die Einstellung
Drücke eine Taste
Sound ist aus.
Sound ist ein.
KBD: Gedrückte Funktionstaste:
KBD: Unbekannte Funktionstaste:
KBD: Unbekannte spezielle Taste:
MEM: Bytes frei/benötigt:
MEM: Nicht genug Speicher!
ROM: AMSDOS verboten.
ROM: AMSDOS+ verboten.
ROM: AMSDOS-Beschleunigung installiert.
ROM: AMSDOS+ Beschleunigung installiert.
ROM: Fehler beim Öffnen der Datei
ROM: Fehler in Datei
ROM: new(): Kein Speicher!
ROM: Kein AMSDOS-ROM gefunden.
ROM: Kein Vordergrund-ROM gefunden.
ROM: ROM schon geladen:
ROM: TAPE-Umleitung installiert.
ROM: Unbekannte ROM-Version.
ROM: CPC 464 gefunden. (c) Amstrad und Locomotive 1984, 1985
ROM: CPC 664 gefunden. (c) Amstrad und Locomotive 1984, 1985
ROM: CPC 6128 gefunden. (c) Amstrad und Locomotive 1984, 1985
ROM: CPC 464+ gefunden. (c) Amstrad und Locomotive 1984, 1985
ROM: CPC 6128+ gefunden. (c) Amstrad und Locomotive 1984, 1985
ROM: KC compact gefunden. (c) Amstrad und Locomotive 1984, 1985
SB: BLASTER-Umgebungsvariable nicht gesetzt!
SB: Warnung: Unbekannte BLASTER-Option
SB: Adlib-Karte gefunden an Adresse:
SB: Keine Adlib-Karte gefunden an Adresse:
SCREEN: Nicht genug Speicher!
SEL: TMP environment variable not set!
SEL: Cannot get TMP file.
SEL: Writing in ZIP file ignored:
SEL: Cannot open file:
SEL: Cannot remove file:
SEL: Cannot rename file:
SEL: File removed:
SELECT: Nicht genug Speicher!
SELECT: Kein Disketten-Abbild!
Letztens gewählt:
Speichern auf Kassette
Laden von Kassette
Katalog
Lade Schnappschuß
Speichere Konfiguration
Lade Konfiguration
Ausgewählte Datei:
Keine Datei ausgewählt.
DATEIAUSWAHL
SETUP: Fehler beim Öffnen der Datei
SETUP: Bitte überschreiben Sie nicht CPCEMU.CFG!
SETUP: Warnung: COMSPEC-Umgebungsvariable nicht gesetzt!
SETUP: Kann Befehl nicht ausführen.
Konfigurationsdatei wurde von CPCEMU (v1.5) erzeugt am
SNAP: Fehler beim Öffnen der Datei
Warnung: Keine Schnappschuß-Datei!
SNAP: Version wird nicht unterstützt:
Schnappschuß-Größe wird nicht unterstützt:
Nicht genug Speicher für einen Schnappschuß der Größe
Lade nur 64KB !!
Vielleicht funktioniert er nicht auf diesem CPC!
Hey, nicht genug RAM vorhanden! Größe auf 64KB geändert.
 wurde auf einem CPC 464 erstellt.
 wurde auf einem CPC 664 erstellt.
 wurde auf einem CPC 6128 erstellt.
 wurde auf einem CPC 464+ erstellt.
 wurde auf einem CPC 6128+ erstellt.
 wurde auf einem KC compact erstellt.
 wurde auf einem CPC ??? erstellt.
SPK: Initialisiert.
SWAP: Bekomme keine Swapdatei. Benutze
SWAP: Kann DOS-Speicherblock nicht verkleinern.
SWAP: Kann Programm nicht im Speicher oder auf Platte auslagern.
SWAP: DOS-Exec-Aufruf fehlgeschlagen.  Fehlernummer
SWAP: Ungültiger Funktionsaufruf.
SWAP: Programmdatei nicht gefunden.
SWAP: Zugriff auf Programmdatei verweigert.
SWAP: Nicht genug Speicher, um Programm zu starten.
SWAP: Ungültige Environment-Variable.
SWAP: Ungültiges Format.
SWAP: Unerwarteter Fehler
ZIF: Unbekannter Fehler!
ZIP: Kann Datei nicht öffnen.
ZIP: Datei zu klein
ZIP: Lesefehler
ZIP: Ende des Haupt-Verzeichnisses nicht gefunden
ZIP: Haupt-Verzeichnis nicht gefunden
ZIP: Multi-Volume nicht unterstützt
ZIP: Header-Marke nicht gefunden
# CPCEMU.MSG ----------------------------------- 2. French
NO TOKEN
#ENDIF
#IFCPC
AMSDOS désactivé
AMSDOS accéléré
Masque de Break
Affichage couleurs
Nom de la firme
Type de CPC
Type de CRTC
Fichier des datas
Lecteur A
Lecteur A : autostart
Lecteur A : face
Lecteur A : protégé en écriture
Lecteur B
Lecteur B : autostart
Lecteur B : face
Lecteur B : protégé en écriture
EMS active
Emulation ralentie
Vitesse du Z80
Fichier d'aide
Fréquence des interruptions
Reprise post-interruption
Calibrer Joystick(0)
Calibrer Joystick(1)
Touches curseur comme joystick 0
Taille du joystick virtuel
Langue du clavier
Langue de l'aide
M4 active
Souris active
Type de souris
Gestion du multimode
Changements de palette
POKEs pour tricher
Secteur sur 50 Hz
Signal d'extension
Impressions
Taille de la RAM
Type d'extension de la RAM
Temps réel
Bloc de ROM
Chemin vers la ROM
Temporisation pour SB
Autre temporisation pour SB
Tampon DMA pour SB
Taux d'échantillonnage pour SB
Stéréo avec SB
Offset de l'écran
Mode d'operation de la carte SD
Afficher la configuration
Snapshot
Type de carte son
Son actif
Effets sonores actif
Dérivation de la cassette
Chemin vers cassette
Chemin vers TMP
Mode graphique
Langue du clavier virtuel
Position de la VSYNC
Menu des Réglages
___Emulation
___Écran
___Son
___M4_Board
___CONTROLES
___PPI
___Divers
Calibrer Joystick(0)
Calibrer Joystick(1)
Lancer le serveur Web
Arretêr le serveur Web
Charger une configuration
Charger un bloc de ROM du firmware
Relancer CPCEMU
Sauvegarder la configuration
POKEs pour tricher
Shell vers le DOS
Continuer
Sauvegarder un Snapshot
Sauvegarder un Snapshot
Taille du Snapshot
Insérer une disquette
Insérer une disquette
Numéro de lecteur
Sélectionner une face
Protection en écriture
Autostart
Choisir fichier ROM
Choisir fichier pour ROM basse
Choisir fichier pour ROM haute
Bloc en fichier
BRK : Erreur de déclaration !
BRK : Point d'arrêt de l'utilisateur (ED FC FC)
CASSETTE : Fichier non ouvert.
CASSETTE : Nom de fichier trop long.
CASSETTE : Fichier : EOF (fin de fichier) trouvé.
CASSETTE : Erreur d'écriture sur fichier.
CASSETTE : On n'a rien sauvegardé.
CASSETTE : On n'a rien chargé.
CASSETTE : Fonction utilisateur inconnue.
CIO : Fichier déjà ouvert :
CIO : Fichier non ouvert :
CIO : Fichier non trouvé :
CIO : Fichier non créé :
CIO : EOF (fin de fichier) dans le fichier
CIO : Erreur en écriture dans le fichier
CIO : Erreur inconnue dans le fichier
CIO : Fichier ouvert avec succès :
CIO : Fichier sauvegardé avec succès :
Base de données de POKEs 
DBASE : Erreur en ouverture
EMS : Erreur d'allocation
EMS : Désolé, il faut au moins LIM EMS 4.0 !
EMS : Non installée.
EMS : Segment standard EMM à :
EMS : Segment physique minimal :
EMS : Nouveau segment physique minimal :
EMS : Page/Segment physique :
 (trop bas)
 pas en fonction
EMS : trouvé 6 pages dans l'ordre
EMS : Utilise segment EMM à :
EMS : Ne peut pas mapper la page
EMS : Pages totales/libres/nécessaires :
EMS : Pages allouées :
EMS : Pas assez de pages libres !
EMS : erreur
EMS : erreur 80 : erreur interne au logiciel
EMS : erreur 81 : mauvais fonctionnement matériel
EMS : erreur 82 : erreur inconnue
EMS : erreur 83 : handle non alloué ou invalide
EMS : erreur 84 : demandé une fonction non définie
EMS : erreur 85 : aucun handle disponible
EMS : erreur 86 : erreur en sauvegardant ou restaurant le contexte de mapping 
EMS : erreur 87 : demandé plus de pages qu'il en existe physiquement
EMS : erreur 88 : demandé plus de pages que disponibles
EMS : erreur 89 : demandé zéro page
EMS : erreur 8A : numéro de page logique invalide
EMS : erreur 8B : numéro de page physique illégal
EMS : erreur 8C : pile contextuelle hors mémoire
EMS : erreur 8D : échec sauvegarde du contexte (handle déjà sur pile)
EMS : erreur 8E : échec restauration du contexte (handle absent de la pile)
EMS : erreur 8F : sous-fonction invalide
EMS : erreur 90 : attribut de type indéfini
EMS : erreur 91 : particularité non supportée
GUS : variable d'environnement ULTRASND non définie !
GUS : échec dans l'initialisation !
Aide
INTRODUCTION
TABLE DES MATIERES
Rubrique non trouvée :
INIT : Désolé, on utilisera la mémoire conventionnelle !
IO_PORT : Numéro de port inconnu :
IO_PORT : Ne peut pas ouvrir le fichier d'impression
IO_PORT: Erreur inconnue
Joystick 0 pas trouvé.
Joystick 1 pas trouvé.
Déplacez le joystick 0 en haut à gauche, appuyez sur le bouton 1 (ou ESC) :
Déplacez le joystick 0 en bas à droite, appuyez sur le bouton 0 (ou ESC) :
Déplacez le joystick 1 en haut à gauche, appuyez sur le bouton 1 (ou ESC) :
Déplacez le joystick 1 en bas à droite, appuyez sur le bouton 0 (ou ESC) :
Utilise le réglage
Appuyez sur une touche
Son désactivé.
Son activé.
KBD : Touche de fonction enfoncée :
KBD: Touche de fonction inconnue :
KBD: Touche spéciale inconnue :
MEM : Octets libres/nécessaires :
MEM : Pas assez de mémoire !
ROM : AMSDOS désactivé.
ROM : AMSDOS+ désactivé.
ROM : accélération de l'AMSDOS installée.
ROM : accélération de l'AMSDOS+ installée.
ROM : Ne peut pas ouvrir le fichier
ROM : Erreur dans le fichier
ROM : nouveau() : pas de mémoire !
ROM : Pas trouvé la ROM de l'AMSDOS.
ROM : Pas trouvé la ROM de premier plan.
ROM : ROM déjà chargée :
ROM : Dérivation CASSETTE installée.
ROM : Version de ROM inconnue.
ROM : CPC 464 détecté. (c) Amstrad and Locomotive 1984, 1985
ROM : CPC 664 détecté. (c) Amstrad and Locomotive 1984, 1985
ROM : CPC 6128 détecté. (c) Amstrad and Locomotive 1984, 1985
ROM : CPC 464+ détecté. (c) Amstrad and Locomotive 1984, 1985
ROM : CPC 6128+ détecté. (c) Amstrad and Locomotive 1984, 1985
ROM : KC compact détecté. (c) Amstrad and Locomotive 1984, 1985
SB : Variable d'environnement BLASTER non définie !
SB : Attention : option BLASTER inconnue !
SB : Carte Adlib trouvée à l'adresse :
SB : Pas de carte Adlib à l'adresse :
ÉCRAN : Pas assez de mémoire !
SEL : variable d'environnement TMP non dénifie !
SEL : pas trouvé le fichier TMP.
SEL : écriture dan le fichier ZIP ignorée :
SEL : impossible d'ouvrir le fichier :
SEL : impossible de supprimer le fichier :
SEL : impossible de renommer le fichier :
SEL : fichier supprimé :
SELECT : Pas assez de mémoire !
SELECT : Ce n'est pas un fichier "Image de disquette" !
Sélectionné la dernière fois :
Sauvegarde sur Cassette
Charge depuis la Cassette
Catalogue
Charge le Snapshot
Sauvegarde la Configuration
Charge la Configuration
Fichier sélectionné :
Aucun fichier sélectionné.
SELECTION DE FICHIER
SETUP : Ne peut pas ouvrir le fichier
SETUP : Impossible d'écraser le fichier originel de configuration CPCEMU.CFG !
SETUP : Attention : variable d'environnement CONSPEC non définie !
SETUP : Ne peut pas exécuter la commande.
Fichier de configuration créé par CPCEMU (v1.5) sur
SNAP : Ne peut pas ouvrir le fichier.
Attention : ce n'est pas un fichier Snapshot !
SNAP : Version non admise :
Taille de Snapshot non admise :
Pas assez de mémoire pour charger un snapshot de
Chargement de 64 K seulement !!
Peut-être qu'il ne tournait pas sur ce CPC !
Pas assez de RAM ! Taille ramenée à 64 K.
 était sauvegardé sur un CPC 464.
 était sauvegardé sur un CPC 664.
 était sauvegardé sur un CPC 6128.
 était sauvegardé sur un CPC 464+.
 était sauvegardé sur un CPC 6128+.
 était sauvegardé sur un KC compact.
 était sauvegardé sur un CPC ???
SPK : Initialisé.
SWAP : Ne peut pas avoir de fichier d'échange. Utilise
SWAP : Ne peut pas diminuer le bloc de mémoire DOS.
SWAP : Ne peut pas sauvegarder le programme en mémoire ou sur disque.
SWAP : Echec avec l'appel au DOS. L'erreur est 
SWAP : Mauvaise fonction.
SWAP : Fichier programme non trouvé.
SWAP : Accès refusé au fichier programme.
SWAP : Mémoire insuffisante pour lancer le programme.
SWAP : Mauvais environnement.
SWAP : Mauvais format.
SWAP : Code d'erreur inattendu
ZIF : Erreur inconnue !
ZIP : Ne peut pas ouvrir le fichier
ZIP : Fichier trop court
ZIP : Erreur en lecture
ZIP : Pas trouvé la fin du répertoire central
ZIP : Pas trouvé le répertoire central
ZIP : Multi-volume non supporté
ZIP : Pas trouvé la signature de l'en-tête central
# CPCEMU.MSG ----------------------------------- 3. Spanish
NO TOKEN
#ENDIF
#IFCPC
AMSDOS Desactivado
AMSDOS Acelerado
Máscara Ruptura
Monitor Color
Fabricante
Modelo CPC
Tipo CRTC
Fichero de Datos
Unidad_A
Unidad_A: autoarranque
Unidad_A: cara
Unidad_A: protegida contra escritura
Unidad_B
Unidad_B: autoarranque
Unidad_B: cara
Unidad_B: protegida contra escritura
EMS Activada
Retardo Emulación
Velocidad Emulación
Fichero de Ayuda
Frecuencia Interrupción
Reanudar Interrupción
Calibrar JOY0
Calibrar JOY1
Teclas de cursor como joystick 0
Dimensión del joystick virtual
Idioma Teclado
Idioma
M4 Activado
Ratón Activado
Tipo Ratón
Actualizar Multimodo
Cambio Paleta
Fichero Pokes
PPI 50Hz
PPI Señal Expansión
Impresora
Tamaño RAM
Tipo de ampliación de la RAM
Tiempo Real
Bloque ROM
Path ROM
Retardo SB
Retardo0 SB
Buffer DMA SB
Vel Muestreo SB 
SB Estéreo
Desplazar Pantalla
Modo de operación de la tarjeta SD
Mostrar Configuración
Snapshot
Dispositivo Sonido
Sonido Activado
Efectos de Sonido Activado
Desvío Cinta
Path Cinta
Path TMP
Modo Video
Idioma Teclado virtual
Posición VSYNC
Menú de configuración
___Emulación
___Pantalla
___Sonido
___M4_Board
___Control
___Opciones PPI
___Miscelánea
Calibrar JOY0
Calibrar JOY1
Arrancar el servidor web
Detener el servidor web
Cargar Configuración
Cargar un bloque ROM de firmware
Reiniciar Emulación
Guardar Configuración
Fichero de Pokes
Shell al DOS
Continuar
Guardar Snapshot
Guardar Snapshot
Dimensión del Snapshot
Insertar Disco
Insertar Disco
Número de Unidad
Seleccionar Cara
Protección contra Escritura
Autoarranque
Seleccionar fichero ROM
Seleccionar fichero por ROM abajo
Seleccionar fichero por ROM arriba
Bloque en fichero
BRK: ¡Error de declaración!
BRK: Breakpoint de usuario (ED FC FC)
CASSETTE: Fichero no abierto
CASSETTE: Nombre de fichero demasiado largo.
CASSETTE: Fichero: EOF encontrado.
CASSETTE: Error escribiendo fichero.
CASSETTE: No se guardo nada.
CASSETTE: No se cargo nada.
CASSETTE: Función de usuario desconocida
CIO: El fichero ya estaba abierto:
CIO: Fichero no abierto:
CIO: Fichero no encontrado:
CIO: Fichero no creado:
CIO: EOF en fichero
CIO: Error escribiendo en fichero
CIO: Error desconocido en fichero
CIO: Fichero cargado correctamente:
CIO: Fichero guardado correctamente:
Fichero de Pokes
DBASE: Error abriendo fichero
EMS: Error de asignación
EMS: Se necesita como mínimo LIM EMS 4.0 
EMS: No instalado.
EMS: Segmento EMM estandar en:
EMS: Segmento físico mínimo:
EMS: Nuevo segmento físico mínimo:
EMS: Página física/segmento:
 (demasiado bajo)
 no esta en orden
EMS: 6 páginas en orden encontradas
EMS: Usando segmento EMM en:
EMS: Imposible mapear página
EMS: Páginas totales/libres/requeridas:
EMS: Páginas asignadas:
EMS: ¡No hay suficientes paginas!
EMS: error
EMS: error 80: error interno de software
EMS: error 81: fallo en hardware
EMS: error 82: error desconocido
EMS: error 83: handle no reservado o desconocido
EMS: error 84: petición de una función no definida
EMS: error 85: no hay handles disponibles
EMS: error 86: error guardando o restaurando contexto de mapeado
EMS: error 87: se han pedido más páginas de las que existen físicamente
EMS: error 88: se han pedido más páginas de las disponibles actualmente
EMS: error 89: cero páginas pedidas
EMS: error 8A: número de página lógica inválido
EMS: error 8B: numero de página física ilegal
EMS: error 8C: memoria insuficiente para stack de contexto
EMS: error 8D: fallo guardando contexto, el handle ya tiene stack de contexto
EMS: error 8E: fallo restaurando contexto, el handle no tiene stack de contexto
EMS: error 8F: subfunción no válida
EMS: error 90: tipo de atributo no definido
EMS: error 91: característica no soportada
GUS: ¡Variable de entorno ULTRASND no definida!
GUS: ¡Fallo de inicialización!
Ayuda
INTRODUCCIóN
TABLA DE CONTENIDOS
Tema no encontrado:
INIT: Usando memoria convencional.
IO_PORT: Número de puerto desconocido:
IO_PORT: No se pudo abrir el fichero de impresora
IO_PORT: Error desconocido
Joystick 0 no encontrado.
Joystick 1 no encontrado.
Joystick 0 en izquierda arriba, y pulse fuego 1 (o ESC):
Joystick 0 en derecha abajo, y pulse fuego 0 (o ESC):
Joystick 1 en izquierda arriba, y pulse fuego 1 (o ESC):
Joystick 1 en derecha abajo, y pulse fuego 0 (o ESC):
Usa los valores
Pulsa una tecla
El sonido está desactivado.
El sonido está activado.
KBD: Tecla de función pulsada:
KBD: Tecla de función desconocida:
KBD: Tecla especial desconocida:
MEM: Bytes libres/requeridos:
MEM: ¡Memoria insuficiente!
ROM: AMSDOS inactivo.
ROM: AMSDOS+ inactivo.
ROM: AMSDOS acelerado instalado.
ROM: AMSDOS+ acelerado instalado.
ROM: No se pudo abrir el fichero
ROM: Error en fichero
ROM: new(): ¡no hay memoria!
ROM: AMSDOS ROM no encontrada.
ROM: ROM de primer plano no encontrada.
ROM: ROM ya estaba cargada:
ROM: Instalada la ignoración del CASETE.
ROM: Version de ROM desconocida.
ROM: CPC 464 detectado. (c) Amstrad and Locomotive 1984, 1985
ROM: CPC 664 detectado. (c) Amstrad and Locomotive 1984, 1985
ROM: CPC 6128 detectado. (c) Amstrad and Locomotive 1984, 1985
ROM: CPC 464+ detectado. (c) Amstrad and Locomotive 1984, 1985
ROM: CPC 6128+ detectado. (c) Amstrad and Locomotive 1984, 1985
ROM: KC compact detectado. (c) Amstrad and Locomotive 1984, 1985
SB: ¡Variable de entorno BLASTER no definida!
SB: Aviso: opción en BLASTER desconocida
SB: Tarjeta Adlib encontrada en la dirección:
SB: No se encontro tarjeta Adlib en la dirección:
SCREEN: ¡Memoria insuficiente!
SEL: ¡Variable de entorno TMP not definida!
SEL: No puede abrirse fichero TMP.
SEL: Escritura en fichero ZIP ignorado:
SEL: No puede abrirse fichero:
SEL: No puede borrarse fichero:
SEL: No puede renombrarse fichero:
SEL: Fichero borrado:
SELECT: ¡Memoria insuficiente!
SELECT: ¡No es un fichero imagen de disco!
Ultima selección:
Guardar en Cinta
Cargar de Cinta
Catálogo
Cargar Snapshot
Guardar Configuración
Cargar Configuración
Fichero seleccionado:
No se ha seleccionado fichero.
SELECCIóN DE FICHEROS
SETUP: No se pudo abrir el fichero
SETUP: ¡No sobreescribir la configuración original CPCEMU.CFG!
SETUP: Aviso: ¡Variable de entorno COMSPEC no definida!
SETUP: No se pudo ejecutar el comando.
Fichero de configuración creado por CPCEMU (v1.5) el
SNAP: No se pudo abrir el fichero
Aviso: ¡No es un fichero snapshot!
SNAP: Versión no soportada:
Tamaño de snapshot no soportado:
Memoria insuficiente para cargar un snapshot de
¡¡ Cargando sólo 64KB !!
¡Quizas no funcione en este CPC!
¡Hey, no tienes bastante RAM! Tamaño cambiado a 64KB.
 fue guardado en un CPC 464.
 fue guardado en un CPC 664.
 fue guardado en un CPC 6128.
 fue guardado en un CPC 464+.
 fue guardado en un CPC 6128+.
 fue guardado en un KC compact.
 fue guardado en un CPC ???
SPK: Inicializado.
SWAP: Error en fichero de intercambio. Usando
SWAP: Imposible reducir bloque de memoria DOS.
SWAP: No se pudo grabar el programa en memoria o disco.
SWAP: Fallo en llamada exec al DOS .  El error es
SWAP: Función incorrecta.
SWAP: Fichero del programa no encontrado.
SWAP: Acceso al fichero de programa denegado.
SWAP: Memoria insuficiente para ejecutar el programa.
SWAP: Entorno incorrecto.
SWAP: Formato incorrecto.
SWAP: Error de código inesperado
ZIF: ¡Error desconocido!
ZIP: Error abriendo fichero
ZIP: Fichero demasiado corto
ZIP: Error en lectura
ZIP: Fin del directorio central no encontrado
ZIP: Directorio central no encontrado
ZIP: Multi volumen no soportado
ZIP: Indentificador de la cabecera central no encontrado
