name: publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: version to compile
        required: true
      release:
        description: si se crea release
        required: false
        default: 'false'

# on:
#   pull_request:
#     branches:
#       - main

jobs:
  publish-release:
    permissions: write-all 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: cpc-config
            asset_name: cpc-config-linux-amd64
          - os: macos-latest
            artifact_name: cpc-config
            asset_name: cpc-config-macos-amd64

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install zip
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: sudo apt-get install zip

    - name: Extract version from VERSION file
      id: extract_version
      run: |
        VERSION=${{ github.event.inputs.version }}
        echo "Version: $VERSION"
        echo "::set-output name=version::$VERSION"
        
    - name: compile catcpc-config2cpc
      run: |
        mkdir dist
        gcc src/cpc-config.c -o dist/cpc-config
        ls -l dist
    
    - name: upload cpc-config
      uses: actions/upload-artifact@v4
      with:
        name: cpc-config-${{ matrix.os }}
        path: dist/cpc-config
  
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      if: ${{ github.event.inputs.release == 'true' }}
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: v${{ steps.extract_version.outputs.version }}
        overwrite: true
        body: "new version"