#!/bin/bash

# Define the variable and its value
VARIABLE_NAME="CPCREADY"
VARIABLE_VALUE="~/CPCReady"

# Determine the shell configuration file to update based on the user's shell
case "$SHELL" in
    */bash) SHELL_CONFIG="$HOME/.bash_profile" ;;
    */zsh) SHELL_CONFIG="$HOME/.zshrc" ;;
    *) SHELL_CONFIG="$HOME/.profile" ;;
esac

# Add the variable to the shell configuration file
if ! grep -q "$VARIABLE_NAME" "$SHELL_CONFIG"; then
    echo "export $VARIABLE_NAME=\"$VARIABLE_VALUE\"" >> "$SHELL_CONFIG"
fi

exit 0
