######################################################
# CPCReady MAkefile version: 1.0
######################################################

CPCREADY_CFG := cfg/cpcready.cfg

# Verificar la existencia del archivo cfg/cpcready.cfg
check_cfg:
    @if [ -f $(CPCREADY_CFG) ]; then \
        echo "El archivo $(CPCREADY_CFG) existe."; \
    else \
        echo "El archivo $(CPCREADY_CFG) no existe en la ruta actual."; \
        exit 1; \
    fi

# Regla build dependiente de check_cfg
build: check_cfg
    @echo "Ejecutando cpcr_build..."
    ./cpcr_build build

clean:
    @echo "Borrando el contenido de la carpeta 'out'..."
    rm -rf out/*
