
name: Upload TEST PYPY.ORG

on:
  pull_request:
    branches:
      - developdd
    types:
      - closed

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install poetry
        pip install -r requirements.txt
        poetry install
        poetry version prerelease

    - name: add configs
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}

    - name: build and publish
      run: |
        poetry publish --build
        


        
