
name: Upload TEST PYPY.ORG

# on:
#   pull_request:
#     types: [closed]
on:
  push:
    branches:
      - 28-añadir-crear-cabecera-amsdos-para-ficheros-basic
# on:
#   pull_request:
#     branches:
#       - develop
#     types:
#       - closed

permissions:
  contents: read

jobs:
    release-build:
      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
          with:
            python-version: "3.x"
  
        - name: build release distributions
          run: |
            python -m pip install --upgrade pip
            python -m build
  
        - name: upload windows dists
          uses: actions/upload-artifact@v3
          with:
            name: release-dists
            path: dist/
  
    pypi-publish:
      runs-on: ubuntu-latest
      needs:
        - release-build
      permissions:
        id-token: write
  
      steps:
        - name: Retrieve release distributions
          uses: actions/download-artifact@v3
          with:
            name: release-dists
            path: dist/
  
        - name: Publish release distributions to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            repository-url: https://test.pypi.org/legacy/


