
name: Upload TEST PYPY.ORG

# on:
#   pull_request:
#     branches:
#       - develop
#     types:
#       - closed

on: [push]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install poetry
        pip install -r requirements.txt
        poetry install


    - name: Run tests
      run: |
        python -m unittest discover -v

    # - name: Build and publish to pypi
    #   uses: JRubics/poetry-publish@v1.17
    #   with:
    #     pypi_token: ${{ secrets.PYPI_TEST_TOKEN }}
    #     repository_name: "cpcready"
    #     repository_url: "https://test.pypi.org/legacy/"

        
