
name: Upload pre-release PYPY.ORG

on:
  pull_request:
    branches:
      - developdd
    types:
      - closed

permissions:
  contents: read

jobs:
  pre-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install poetry
        pip install -r requirements.txt
        poetry install
        poetry version prerelease

    - name: add configs
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
    - name: Extract version from INI
      run: |
            VERSION=$(grep -oP '(?<=version = ")[^"]*' pyproject.toml)
            echo "VERSION=$VERSION" >> $GITHUB_ENV
    - name: Use the version variable
      run: echo "__version__ = '${{ env.VERSION }}'" > CPCReady/__init__.py

    - name: build and publish
      run: |
        poetry publish --build
        


        
