
name: Executing TEST

on: [push]

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install poetry
        pip install -r requirements.txt
        poetry install
        poetry version prerelease

    - name: Run tests
      run: |
        python -m unittest discover -v

    # - name: add configs
    #   run: |
    #     poetry config repositories.test-pypi https://test.pypi.org/legacy/
    #     poetry config pypi-token.test-pypi ${{ secrets.PYPI_TEST_TOKEN }}

    # - name: build and publish
    #   run: |
    #     poetry publish -r test-pypi --build
        


        
